# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.6
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Metrics/BlockLength:
#   Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
